#!/usr/bin/env python3
"""Definición única de las medidas DAX. La consumen build_measures_dax.py
(genera dax/measures.dax) y build_pbip.py (las incrusta en el modelo PBIP),
para que ambos queden siempre sincronizados."""

# (nombre, formatString|None, [líneas DAX])  — sin la cabecera "Nombre ="
MEASURES = [
    ("KPI Value", None, [
        'VAR vt = SELECTEDVALUE ( Dim_KPI[Value_Type] )',
        'VAR n  = SUM ( Fact_Scorecard[Numerator] )',
        'VAR d  = SUM ( Fact_Scorecard[Denominator] )',
        'RETURN',
        '    SWITCH (',
        '        vt,',
        '        "PCT",      DIVIDE ( n, d ),',
        '        "RATE1000", DIVIDE ( n, d ) * 1000,',
        '        "RATIO",    DIVIDE ( n, d ),',
        '        "CURRENCY", n,',
        '        "COUNT",    n,',
        '        n',
        '    )',
    ]),
    ("KPI Value (fmt)", None, [
        'VAR v  = [KPI Value]',
        'VAR vt = SELECTEDVALUE ( Dim_KPI[Value_Type] )',
        'RETURN',
        '    IF (',
        '        ISBLANK ( v ), "-",',
        '        SWITCH (',
        '            vt,',
        '            "PCT",      FORMAT ( v, "0.0%" ),',
        '            "RATE1000", FORMAT ( v, "#,##0.0" ) & " /1k",',
        '            "RATIO",    FORMAT ( v, "#,##0.00" ),',
        '            "CURRENCY", FORMAT ( v, "#,##0" ) & " k€",',
        '            "COUNT",    FORMAT ( v, "#,##0" ),',
        '            FORMAT ( v, "#,##0.00" )',
        '        )',
        '    )',
    ]),
    ("KPI Target", None, [
        'SELECTEDVALUE ( Dim_KPI[Target] )',
    ]),
    ("Variance to Target", None, [
        'IF ( ISBLANK ( [KPI Target] ), BLANK (), [KPI Value] - [KPI Target] )',
    ]),
    ("Variance %", "0.0%", [
        'DIVIDE ( [KPI Value] - [KPI Target], [KPI Target] )',
    ]),
    ("RAG Status", None, [
        'VAR v   = [KPI Value]',
        'VAR t   = [KPI Target]',
        'VAR dir = SELECTEDVALUE ( Dim_KPI[Direction] )',
        'RETURN',
        '    SWITCH (',
        '        TRUE (),',
        '        ISBLANK ( v ) || ISBLANK ( t ) || dir = "N", "No target",',
        '        dir = "H" && v >= t,        "Green",',
        '        dir = "H" && v >= t * 0.95, "Amber",',
        '        dir = "H",                  "Red",',
        '        dir = "L" && v <= t,        "Green",',
        '        dir = "L" && v <= t * 1.05, "Amber",',
        '        dir = "L",                  "Red",',
        '        "No target"',
        '    )',
    ]),
    ("RAG Color", None, [
        'SWITCH (',
        '    [RAG Status],',
        '    "Green",     "#2E7D32",',
        '    "Amber",     "#F9A825",',
        '    "Red",       "#C62828",',
        '    "No target", "#9E9E9E",',
        '    "#9E9E9E"',
        ')',
    ]),
    ("KPI Value PM", None, [
        '// Mes anterior por índice de mes (no requiere marcar tabla de fechas)',
        'VAR idx = SELECTEDVALUE ( Dim_Date[Month_Index] )',
        'RETURN',
        '    CALCULATE (',
        '        [KPI Value],',
        '        REMOVEFILTERS ( Dim_Date ),',
        '        Dim_Date[Month_Index] = idx - 1',
        '    )',
    ]),
    ("MoM Change", None, [
        'IF ( ISBLANK ( [KPI Value PM] ), BLANK (), [KPI Value] - [KPI Value PM] )',
    ]),
    ("MoM Change %", "0.0%", [
        'DIVIDE ( [KPI Value] - [KPI Value PM], [KPI Value PM] )',
    ]),
    ("Trend Arrow", None, [
        'VAR delta = [KPI Value] - [KPI Value PM]',
        'VAR base  = [KPI Value PM]',
        'VAR pct   = DIVIDE ( delta, ABS ( base ) )',
        'RETURN',
        '    SWITCH (',
        '        TRUE (),',
        '        ISBLANK ( [KPI Value PM] ) || ISBLANK ( [KPI Value] ), "",',
        '        ABS ( pct ) < 0.005, "→",',
        '        delta > 0,           "↗",',
        '        "↘"',
        '    )',
    ]),
    ("Trend Color", None, [
        'VAR delta = [KPI Value] - [KPI Value PM]',
        'VAR dir   = SELECTEDVALUE ( Dim_KPI[Direction] )',
        'RETURN',
        '    SWITCH (',
        '        TRUE (),',
        '        dir = "N" || ISBLANK ( delta ) || delta = 0, "#9E9E9E",',
        '        ( dir = "H" && delta > 0 ) || ( dir = "L" && delta < 0 ), "#2E7D32",',
        '        "#C62828"',
        '    )',
    ]),
    ("KPI Value YTD", None, [
        '// YTD del año fiscal DS Smith (mayo-abril)',
        'VAR fy     = SELECTEDVALUE ( Dim_Date[Fiscal_Year] )',
        'VAR maxIdx = MAX ( Dim_Date[Month_Index] )',
        'RETURN',
        '    CALCULATE (',
        '        [KPI Value],',
        '        REMOVEFILTERS ( Dim_Date ),',
        '        Dim_Date[Fiscal_Year] = fy,',
        '        Dim_Date[Month_Index] <= maxIdx',
        '    )',
    ]),
    ("KPIs Green", "0", [
        'SUMX ( VALUES ( Dim_KPI[KPI_ID] ), IF ( [RAG Status] = "Green", 1, 0 ) )',
    ]),
    ("KPIs Amber", "0", [
        'SUMX ( VALUES ( Dim_KPI[KPI_ID] ), IF ( [RAG Status] = "Amber", 1, 0 ) )',
    ]),
    ("KPIs Red", "0", [
        'SUMX ( VALUES ( Dim_KPI[KPI_ID] ), IF ( [RAG Status] = "Red", 1, 0 ) )',
    ]),
    ("KPIs Measured", "0", [
        'SUMX ( VALUES ( Dim_KPI[KPI_ID] ), IF ( NOT ISBLANK ( [KPI Value] ), 1, 0 ) )',
    ]),
    ("% On Target", "0.0%", [
        'DIVIDE ( [KPIs Green], [KPIs Green] + [KPIs Amber] + [KPIs Red] )',
    ]),
    ("Selected Month Label", None, [
        '"A fecha de " & FORMAT ( MAX ( Dim_Date[Date] ), "MMM yyyy" )',
    ]),
]
