{
  "name": "Scorecard",
  "compatibilityLevel": 1567,
  "model": {
    "culture": "en-US",
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "sourceQueryCulture": "en-US",
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "expressions": [
      {
        "name": "SourceFile",
        "kind": "m",
        "expression": [
          "\"C:\\Users\\esangesc\\Downloads\\powerbiscorecard\\powerbi-scorecard\\data\\Scorecard_Model.xlsx\"",
          "  meta [IsParameterQuery=true, Type=\"Text\", IsParameterQueryRequired=true]"
        ]
      }
    ],
    "tables": [
      {
        "name": "Dim_KPI",
        "columns": [
          {
            "name": "KPI_ID",
            "dataType": "string",
            "sourceColumn": "KPI_ID",
            "summarizeBy": "none"
          },
          {
            "name": "Perspective",
            "dataType": "string",
            "sourceColumn": "Perspective",
            "summarizeBy": "none"
          },
          {
            "name": "Perspective_Objective",
            "dataType": "string",
            "sourceColumn": "Perspective_Objective",
            "summarizeBy": "none"
          },
          {
            "name": "Objective",
            "dataType": "string",
            "sourceColumn": "Objective",
            "summarizeBy": "none"
          },
          {
            "name": "Process",
            "dataType": "string",
            "sourceColumn": "Process",
            "summarizeBy": "none"
          },
          {
            "name": "Measure",
            "dataType": "string",
            "sourceColumn": "Measure",
            "summarizeBy": "none"
          },
          {
            "name": "Definition",
            "dataType": "string",
            "sourceColumn": "Definition",
            "summarizeBy": "none"
          },
          {
            "name": "Value_Type",
            "dataType": "string",
            "sourceColumn": "Value_Type",
            "summarizeBy": "none"
          },
          {
            "name": "Unit",
            "dataType": "string",
            "sourceColumn": "Unit",
            "summarizeBy": "none"
          },
          {
            "name": "Direction",
            "dataType": "string",
            "sourceColumn": "Direction",
            "summarizeBy": "none"
          },
          {
            "name": "Target",
            "dataType": "double",
            "sourceColumn": "Target",
            "summarizeBy": "none"
          },
          {
            "name": "Has_Data",
            "dataType": "string",
            "sourceColumn": "Has_Data",
            "summarizeBy": "none"
          }
        ],
        "partitions": [
          {
            "name": "Dim_KPI",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(SourceFile), null, true),",
                "    Nav = Source{[Item=\"Dim_KPI\",Kind=\"Table\"]}[Data],",
                "    Typed = Table.TransformColumnTypes(Nav, {{\"KPI_ID\", type text}, {\"Perspective\", type text}, {\"Perspective_Objective\", type text}, {\"Objective\", type text}, {\"Process\", type text}, {\"Measure\", type text}, {\"Definition\", type text}, {\"Value_Type\", type text}, {\"Unit\", type text}, {\"Direction\", type text}, {\"Target\", type number}, {\"Has_Data\", type text}})",
                "in",
                "    Typed"
              ]
            }
          }
        ]
      },
      {
        "name": "Dim_Date",
        "columns": [
          {
            "name": "Date",
            "dataType": "dateTime",
            "sourceColumn": "Date",
            "summarizeBy": "none"
          },
          {
            "name": "Year",
            "dataType": "int64",
            "sourceColumn": "Year",
            "summarizeBy": "none"
          },
          {
            "name": "Month",
            "dataType": "int64",
            "sourceColumn": "Month",
            "summarizeBy": "none"
          },
          {
            "name": "Month_Name",
            "dataType": "string",
            "sourceColumn": "Month_Name",
            "summarizeBy": "none"
          },
          {
            "name": "Quarter",
            "dataType": "string",
            "sourceColumn": "Quarter",
            "summarizeBy": "none"
          },
          {
            "name": "Fiscal_Year",
            "dataType": "string",
            "sourceColumn": "Fiscal_Year",
            "summarizeBy": "none"
          },
          {
            "name": "Month_Index",
            "dataType": "int64",
            "sourceColumn": "Month_Index",
            "summarizeBy": "none"
          }
        ],
        "partitions": [
          {
            "name": "Dim_Date",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(SourceFile), null, true),",
                "    Nav = Source{[Item=\"Dim_Date\",Kind=\"Table\"]}[Data],",
                "    Typed = Table.TransformColumnTypes(Nav, {{\"Date\", type datetime}, {\"Year\", Int64.Type}, {\"Month\", Int64.Type}, {\"Month_Name\", type text}, {\"Quarter\", type text}, {\"Fiscal_Year\", type text}, {\"Month_Index\", Int64.Type}})",
                "in",
                "    Typed"
              ]
            }
          }
        ]
      },
      {
        "name": "Fact_Scorecard",
        "columns": [
          {
            "name": "KPI_ID",
            "dataType": "string",
            "sourceColumn": "KPI_ID",
            "summarizeBy": "none"
          },
          {
            "name": "Date",
            "dataType": "dateTime",
            "sourceColumn": "Date",
            "summarizeBy": "none"
          },
          {
            "name": "Numerator",
            "dataType": "double",
            "sourceColumn": "Numerator",
            "summarizeBy": "sum"
          },
          {
            "name": "Denominator",
            "dataType": "double",
            "sourceColumn": "Denominator",
            "summarizeBy": "sum"
          }
        ],
        "partitions": [
          {
            "name": "Fact_Scorecard",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(SourceFile), null, true),",
                "    Nav = Source{[Item=\"Fact_Scorecard\",Kind=\"Table\"]}[Data],",
                "    Typed = Table.TransformColumnTypes(Nav, {{\"KPI_ID\", type text}, {\"Date\", type datetime}, {\"Numerator\", type number}, {\"Denominator\", type number}})",
                "in",
                "    Typed"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "KPI Value",
            "expression": [
              "VAR vt = SELECTEDVALUE ( Dim_KPI[Value_Type] )",
              "VAR n  = SUM ( Fact_Scorecard[Numerator] )",
              "VAR d  = SUM ( Fact_Scorecard[Denominator] )",
              "RETURN",
              "    SWITCH (",
              "        vt,",
              "        \"PCT\",      DIVIDE ( n, d ),",
              "        \"RATE1000\", DIVIDE ( n, d ) * 1000,",
              "        \"RATIO\",    DIVIDE ( n, d ),",
              "        \"CURRENCY\", n,",
              "        \"COUNT\",    n,",
              "        n",
              "    )"
            ]
          },
          {
            "name": "KPI Value (fmt)",
            "expression": [
              "VAR v  = [KPI Value]",
              "VAR vt = SELECTEDVALUE ( Dim_KPI[Value_Type] )",
              "RETURN",
              "    IF (",
              "        ISBLANK ( v ), \"-\",",
              "        SWITCH (",
              "            vt,",
              "            \"PCT\",      FORMAT ( v, \"0.0%\" ),",
              "            \"RATE1000\", FORMAT ( v, \"#,##0.0\" ) & \" /1k\",",
              "            \"RATIO\",    FORMAT ( v, \"#,##0.00\" ),",
              "            \"CURRENCY\", FORMAT ( v, \"#,##0\" ) & \" k€\",",
              "            \"COUNT\",    FORMAT ( v, \"#,##0\" ),",
              "            FORMAT ( v, \"#,##0.00\" )",
              "        )",
              "    )"
            ]
          },
          {
            "name": "KPI Target",
            "expression": [
              "SELECTEDVALUE ( Dim_KPI[Target] )"
            ]
          },
          {
            "name": "Variance to Target",
            "expression": [
              "IF ( ISBLANK ( [KPI Target] ), BLANK (), [KPI Value] - [KPI Target] )"
            ]
          },
          {
            "name": "Variance %",
            "expression": [
              "DIVIDE ( [KPI Value] - [KPI Target], [KPI Target] )"
            ],
            "formatString": "0.0%"
          },
          {
            "name": "RAG Status",
            "expression": [
              "VAR v   = [KPI Value]",
              "VAR t   = [KPI Target]",
              "VAR dir = SELECTEDVALUE ( Dim_KPI[Direction] )",
              "RETURN",
              "    SWITCH (",
              "        TRUE (),",
              "        ISBLANK ( v ) || ISBLANK ( t ) || dir = \"N\", \"No target\",",
              "        dir = \"H\" && v >= t,        \"Green\",",
              "        dir = \"H\" && v >= t * 0.95, \"Amber\",",
              "        dir = \"H\",                  \"Red\",",
              "        dir = \"L\" && v <= t,        \"Green\",",
              "        dir = \"L\" && v <= t * 1.05, \"Amber\",",
              "        dir = \"L\",                  \"Red\",",
              "        \"No target\"",
              "    )"
            ]
          },
          {
            "name": "RAG Color",
            "expression": [
              "SWITCH (",
              "    [RAG Status],",
              "    \"Green\",     \"#2E7D32\",",
              "    \"Amber\",     \"#F9A825\",",
              "    \"Red\",       \"#C62828\",",
              "    \"No target\", \"#9E9E9E\",",
              "    \"#9E9E9E\"",
              ")"
            ]
          },
          {
            "name": "KPI Value PM",
            "expression": [
              "// Mes anterior por índice de mes (no requiere marcar tabla de fechas)",
              "VAR idx = SELECTEDVALUE ( Dim_Date[Month_Index] )",
              "RETURN",
              "    CALCULATE (",
              "        [KPI Value],",
              "        REMOVEFILTERS ( Dim_Date ),",
              "        Dim_Date[Month_Index] = idx - 1",
              "    )"
            ]
          },
          {
            "name": "MoM Change",
            "expression": [
              "IF ( ISBLANK ( [KPI Value PM] ), BLANK (), [KPI Value] - [KPI Value PM] )"
            ]
          },
          {
            "name": "MoM Change %",
            "expression": [
              "DIVIDE ( [KPI Value] - [KPI Value PM], [KPI Value PM] )"
            ],
            "formatString": "0.0%"
          },
          {
            "name": "Trend Arrow",
            "expression": [
              "VAR delta = [KPI Value] - [KPI Value PM]",
              "VAR base  = [KPI Value PM]",
              "VAR pct   = DIVIDE ( delta, ABS ( base ) )",
              "RETURN",
              "    SWITCH (",
              "        TRUE (),",
              "        ISBLANK ( [KPI Value PM] ) || ISBLANK ( [KPI Value] ), \"\",",
              "        ABS ( pct ) < 0.005, \"→\",",
              "        delta > 0,           \"↗\",",
              "        \"↘\"",
              "    )"
            ]
          },
          {
            "name": "Trend Color",
            "expression": [
              "VAR delta = [KPI Value] - [KPI Value PM]",
              "VAR dir   = SELECTEDVALUE ( Dim_KPI[Direction] )",
              "RETURN",
              "    SWITCH (",
              "        TRUE (),",
              "        dir = \"N\" || ISBLANK ( delta ) || delta = 0, \"#9E9E9E\",",
              "        ( dir = \"H\" && delta > 0 ) || ( dir = \"L\" && delta < 0 ), \"#2E7D32\",",
              "        \"#C62828\"",
              "    )"
            ]
          },
          {
            "name": "KPI Value YTD",
            "expression": [
              "// YTD del año fiscal DS Smith (mayo-abril)",
              "VAR fy     = SELECTEDVALUE ( Dim_Date[Fiscal_Year] )",
              "VAR maxIdx = MAX ( Dim_Date[Month_Index] )",
              "RETURN",
              "    CALCULATE (",
              "        [KPI Value],",
              "        REMOVEFILTERS ( Dim_Date ),",
              "        Dim_Date[Fiscal_Year] = fy,",
              "        Dim_Date[Month_Index] <= maxIdx",
              "    )"
            ]
          },
          {
            "name": "KPIs Green",
            "expression": [
              "SUMX ( VALUES ( Dim_KPI[KPI_ID] ), IF ( [RAG Status] = \"Green\", 1, 0 ) )"
            ],
            "formatString": "0"
          },
          {
            "name": "KPIs Amber",
            "expression": [
              "SUMX ( VALUES ( Dim_KPI[KPI_ID] ), IF ( [RAG Status] = \"Amber\", 1, 0 ) )"
            ],
            "formatString": "0"
          },
          {
            "name": "KPIs Red",
            "expression": [
              "SUMX ( VALUES ( Dim_KPI[KPI_ID] ), IF ( [RAG Status] = \"Red\", 1, 0 ) )"
            ],
            "formatString": "0"
          },
          {
            "name": "KPIs Measured",
            "expression": [
              "SUMX ( VALUES ( Dim_KPI[KPI_ID] ), IF ( NOT ISBLANK ( [KPI Value] ), 1, 0 ) )"
            ],
            "formatString": "0"
          },
          {
            "name": "% On Target",
            "expression": [
              "DIVIDE ( [KPIs Green], [KPIs Green] + [KPIs Amber] + [KPIs Red] )"
            ],
            "formatString": "0.0%"
          },
          {
            "name": "Selected Month Label",
            "expression": [
              "\"A fecha de \" & FORMAT ( MAX ( Dim_Date[Date] ), \"MMM yyyy\" )"
            ]
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "c0745b56-e1f6-462d-9665-044b8372d0ff",
        "fromTable": "Fact_Scorecard",
        "fromColumn": "KPI_ID",
        "toTable": "Dim_KPI",
        "toColumn": "KPI_ID"
      },
      {
        "name": "dacada6c-c415-4671-8c06-188744aca7a8",
        "fromTable": "Fact_Scorecard",
        "fromColumn": "Date",
        "toTable": "Dim_Date",
        "toColumn": "Date"
      }
    ],
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"SourceFile\", \"Dim_KPI\", \"Dim_Date\", \"Fact_Scorecard\"]"
      }
    ]
  }
}